version: "3"

services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booking_management
    ports:
      - 8000:8080
    restart: always
    depends_on:
        - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_management
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
